const express=require("express");
const router=express.Router();
const auth=require("../middleware/authMiddleware");
const admin=require("../middleware/adminMiddleware");
const controller=require("../controllers/resultController");
router.get("/my-results",auth,controller.getResults);
router.get("/",auth,controller.getResults);
router.post("/",auth,admin,controller.createResult);
router.get("/:id/view",auth,controller.viewResult);
router.get("/:id/download",auth,controller.downloadResult);
router.put("/:id",auth,admin,controller.updateResult);
router.delete("/:id",auth,admin,controller.deleteResult);
module.exports=router;
